/** @jsxImportSource @emotion/react */
import Head from 'next/head'
import About from "./about";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cassandra Sibley</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <About />
      </main>

      <footer>
      </footer>
    </div>
  )
}
